extends:
  - spectral:oas
  - spectral:asyncapi

rules:
  info-contact: off  # Disables the requirement for a contact field in OpenAPI
  info-license: error # Ensures that an OpenAPI spec must have a license defined
  info-description:
    description: "OpenAPI info object must have a description."
    severity: warn
    given: "$.info"
    then:
      field: description
      function: truthy

  no-http: 
    description: "All API URLs must use HTTPS."
    severity: error
    given: "$..servers[*].url"
    then:
      function: pattern
      functionOptions:
        match: "^https://"

  no-example-value-and-externalValue:
    description: "Either 'example' or 'externalValue' should be used, but not both."
    severity: error
    given: "$..examples[*]"
    then:
      function: xor
      functionOptions:
        properties:
          - value
          - externalValue

  parameters-kebab-case:
    description: "Parameters should be in kebab-case (lowercase with hyphens)."
    severity: warn
    given: "$..parameters[*].name"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z]+(-[a-z]+)*$"

functionsDir: ./spectral-rules # Custom Spectral functions directory (if needed)
